"""empty message

Revision ID: 54f0f8a0c141
Revises: f4054257c175
Create Date: 2023-12-09 12:47:50.992655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f0f8a0c141'
down_revision: Union[str, None] = 'f4054257c175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login_code', 'word_box',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login_code', 'word_box',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
