"""empty message

Revision ID: 676a4b147fb3
Revises: 2f4cc18dac67
Create Date: 2023-12-13 13:37:46.203723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676a4b147fb3'
down_revision: Union[str, None] = '2f4cc18dac67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_code', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_code', 'is_active')
    # ### end Alembic commands ###
