"""empty message

Revision ID: 7c0a922f8d0b
Revises: e5a344aa1cfe
Create Date: 2023-12-11 05:57:46.275959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0a922f8d0b'
down_revision: Union[str, None] = 'e5a344aa1cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('login_code', sa.String(), nullable=True))
    op.drop_column('students', 'Login_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('Login_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'login_code')
    # ### end Alembic commands ###
