"""empty message

Revision ID: 8715fffe62bb
Revises: 3b0db25dcefe
Create Date: 2023-12-09 09:51:37.207688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8715fffe62bb'
down_revision: Union[str, None] = '3b0db25dcefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login_code', 'expired_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login_code', 'expired_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
