"""empty message

Revision ID: cd95f86cfb4b
Revises: 7b9f41442135
Create Date: 2023-12-11 05:52:25.092784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd95f86cfb4b'
down_revision: Union[str, None] = '7b9f41442135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('Login_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'Login_code')
    # ### end Alembic commands ###
