"""empty message

Revision ID: f4054257c175
Revises: 6d5c27133aa8
Create Date: 2023-12-09 12:47:22.363638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4054257c175'
down_revision: Union[str, None] = '6d5c27133aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_code', sa.Column('word_box', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_code', 'word_box')
    # ### end Alembic commands ###
